kind: Secret
apiVersion: v1
metadata:
  name: backstage-dynamic-plugins-npmrc
  labels:
    {{- include "developer-hub.labels" . | nindent 4 }}
  annotations:
    {{- include "developer-hub.argocd-syncwave" . | nindent 4 }}
stringData:
  .npmrc: '@redhat:registry=https://npm.registry.redhat.com'
type: Opaque
