kind: ConfigMap
metadata:
  name: dh-config-template
  annotations:
    {{- include "developer-hub-prereqs.argocd-syncwave" . | nindent 4 }}
apiVersion: v1
data:
  playbook.yaml: |
    ---
    - name: DH Config templates
      hosts: localhost
      tasks:
        - name: Check existence of group
          ansible.builtin.uri:
            url: https://root:{{ $.Values.gitlab.rootPassword }}@{{ $.Values.gitlab.host }}/api/v4/groups/{{ $.Values.configTemplate.group }}
            method: GET
            validate_certs: false
          register: r_liveness
          retries: 120
          delay: 10
          until: r_liveness.status == 200

        - name: Git config email
          ansible.builtin.command: git config --global user.email "{{ $.Values.gitlab.email.address }}"
          ignore_errors: true

        - name: Git config name
          ansible.builtin.command: git config --global user.name "{{ $.Values.gitlab.email.displayName }}"
          ignore_errors: true

        - name: Build git repo url
          ansible.builtin.set_fact:
            _git_template_repo_url: https://root:{{ $.Values.gitlab.rootPassword }}@{{ $.Values.gitlab.host }}/{{ $.Values.configTemplate.group }}/{{ $.Values.configTemplate.repo }}

        - name: Remove older repo folders
          shell: rm -rf /tmp/{{ $.Values.configTemplate.repo }}

        - name: Check existence of git repo
          ansible.builtin.uri:
            url: '{{ "{{" }} _git_template_repo_url {{ "}}" }}'
            method: GET
            validate_certs: false
          register: r_liveness
          retries: 60
          delay: 10
          until: r_liveness.status == 200

        - name: Clone {{ $.Values.configTemplate.repo }}
          ansible.builtin.git:
            accept_hostkey: true
            force: true
            repo: '{{ "{{" }} _git_template_repo_url {{ "}}" }}'
            dest: "/tmp/{{ $.Values.configTemplate.repo }}"
            version: "{{ $.Values.configTemplate.branch }}"
          environment:
            GIT_SSL_NO_VERIFY: "true"
          register: r_git_clone
          retries: 60
          delay: 10
          until: r_git_clone is not failed

{{- range $item := .Values.configTemplate.templates }}

        - name: Fetch /tmp/{{ $.Values.configTemplate.repo }}/{{ $item }} template from remote host
          run_once: true
          ansible.builtin.fetch:
            src: /tmp/{{ $.Values.configTemplate.repo }}/{{ $item }}
            dest: /tmp/{{ $item }}
            flat: true
            fail_on_missing: true

        - name: Apply template /tmp/{{ $.Values.configTemplate.repo }}/{{ $item }}
          ansible.builtin.template:
            src: /tmp/{{ $item }}
            dest: /tmp/{{ $.Values.configTemplate.repo }}/{{ $item }}
            mode: "0660"
          vars:
            cluster_subdomain: "{{ $.Values.cluster.subdomain }}"
            backstage_host: "{{ $.Values.backstage.host }}"
            gitlab_host: "{{ $.Values.gitlab.host }}"
            argocd_host: "{{ $.Values.gitops.host }}"
            kubernetes_api_url: "{{ $.Values.kubernetes.api }}"
{{- end }}

        - name: Add new files to the repository
          ansible.builtin.command:
            chdir: >-
              /tmp/{{ $.Values.configTemplate.repo }}
            cmd: "git add ."
          ignore_errors: true

        - name: Commit changes to the repository
          ansible.builtin.command:
            chdir: >-
              /tmp/{{ $.Values.configTemplate.repo }}
            cmd: >-
              git commit -a -m 'dh-config init: render env-specific values.'
          ignore_errors: true

        - name: Push all changes back to the project repository
          ansible.builtin.command:
            chdir: >-
              /tmp/{{ $.Values.configTemplate.repo }}
            cmd: >-
              git push {{ "{{" }} _git_template_repo_url {{ "}}" }}
